@extends('layouts.blog')
@section('title','Avis '.$tool->name.' : fonctionnalités, prix et limites')
@section('description',$tool->description ?: 'Découvrez '.$tool->name.', ses fonctionnalités et ses tarifs vérifiés.')
@push('head')<script type="application/ld+json">{!! json_encode(['@context'=>'https://schema.org','@type'=>'SoftwareApplication','name'=>$tool->name,'applicationCategory'=>'BusinessApplication','url'=>$tool->website_url,'offers'=>$tool->plans->map(fn($p)=>['@type'=>'Offer','price'=>$p->monthly_price ?? $p->annual_total,'priceCurrency'=>$p->currency])->values()],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE) !!}</script>@endpush
@section('content')
<article class="tool-detail"><header><a href="{{ route('tools.index') }}">← Tous les outils</a><div><span class="tool-big-logo">{{ strtoupper(substr($tool->name,0,1)) }}</span><div><span class="eyebrow dark">Fiche logiciel vérifiée</span><h1>{{ $tool->name }}</h1><p>{{ $tool->positioning ?: $tool->description ?: 'Informations en cours de structuration.' }}</p></div></div><aside><span>Dernière collecte</span><strong>{{ $tool->last_crawled_at?->translatedFormat('d F Y') ?? 'Non communiqué' }}</strong><a href="{{ $tool->affiliate_url ?: $tool->website_url }}" target="_blank" rel="sponsored noopener">Visiter le site officiel ↗</a></aside></header>
    <div class="tool-content-grid"><main><section><h2>Présentation</h2><p>{{ $tool->description ?: 'Cette fiche est alimentée par les pages officielles collectées. Les informations non vérifiées ne sont pas affichées.' }}</p></section><section class="pros-cons"><div><h2>Points forts</h2><ul>@forelse($tool->strengths ?? [] as $item)<li>✓ {{ $item }}</li>@empty<li>Non communiqué</li>@endforelse</ul></div><div><h2>Limites</h2><ul>@forelse($tool->limitations ?? [] as $item)<li>— {{ $item }}</li>@empty<li>Non communiqué</li>@endforelse</ul></div></section><section><h2>Fonctionnalités documentées</h2><div class="feature-grid">@forelse($tool->features ?? [] as $feature)<span>{{ $feature }}</span>@empty<p>Les fonctionnalités structurées seront complétées après validation des preuves.</p>@endforelse</div></section></main><aside class="tool-side"><div class="price-summary"><span>Tarif à partir de</span><strong>@php($min=$tool->plans->whereNotNull('monthly_price')->min('monthly_price')){{ $min !== null ? $min.' '.$tool->currency.'/mois' : 'Non communiqué' }}</strong><a href="{{ route('tools.pricing',$tool->slug) }}">Voir tous les tarifs →</a></div><div class="source-summary"><strong>{{ $tool->sourcePages->count() }} sources vérifiées</strong>@foreach($tool->sourcePages->take(5) as $source)<a href="{{ $source->url }}" target="_blank" rel="noopener">{{ Str::limit($source->title,35) }} ↗</a>@endforeach</div></aside></div>
</article>
@endsection
