<div class="dashboard-page os-page">
    <section class="page-heading"><div><span class="eyebrow dark">Éditeur par blocs</span><h1>{{ $article ? 'Modifier l’article' : 'Nouvel article' }}</h1><p>Le bloc tarifaire reste connecté aux derniers prix validés.</p></div><a class="secondary-link" href="{{ route('admin.articles') }}" wire:navigate>← Bibliothèque</a></section>
    @if($message)<div class="alert success">✓ {{ $message }}</div>@endif
    @if($errors->any())<div class="alert danger"><strong>Enregistrement impossible</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form wire:submit="save" class="editor-layout"><article class="panel editor-main"><div class="os-form one-column editor-form">
        <div class="field"><label>Titre</label><input wire:model.live.debounce.400ms="title" placeholder="Titre de l’article">@error('title')<small class="field-error">{{ $message }}</small>@enderror</div>
        <div class="field"><label>Slug</label><div class="slug-input"><span>/blog/</span><input wire:model="slug"></div>@error('slug')<small class="field-error">{{ $message }}</small>@enderror</div>
        <div class="field"><label>Extrait</label><textarea wire:model="excerpt" rows="3" placeholder="Résumé affiché dans les listes"></textarea></div>
        <div class="field"><label>Contenu Markdown</label><textarea wire:model="body" class="content-editor" rows="24" placeholder="# Introduction&#10;&#10;Votre contenu…"></textarea>@error('body')<small class="field-error">{{ $message }}</small>@enderror</div>
        <div class="block-toggle"><label><input type="checkbox" wire:model="includePricing"><span><b>▦ Tableau tarifaire dynamique</b><small>Injecte les derniers plans actifs de l’outil au rendu, sans dupliquer les prix.</small></span></label></div>
    </div></article><aside class="editor-sidebar"><article class="panel os-form one-column editor-settings"><h3>Publication</h3><div class="field"><label>Projet / outil</label></div><div class="field"><label>Type</label><select wire:model="type"><option value="tool_review">Fiche outil</option><option value="pricing">Tarifs</option><option value="comparison">Comparatif</option><option value="best_tools">Meilleurs outils</option><option value="alternatives">Alternatives</option><option value="informational">Guide</option><option value="pilier">Page Hub Métier (Pilier)</option></select></div><div class="field"><label>Statut</label><select wire:model.live="status"><option value="draft">Brouillon</option><option value="review">À relire</option><option value="scheduled">Programmé</option><option value="published">Publié</option><option value="archived">Archivé</option></select></div>@if($status==='scheduled')<div class="field"><label>Date de publication</label><input wire:model="scheduledAt" type="datetime-local"></div>@endif<button class="primary-button form-submit" type="submit" wire:loading.attr="disabled" wire:target="save"><span wire:loading.remove wire:target="save">{{ $status === 'published' ? 'Enregistrer et publier' : 'Enregistrer' }}</span><span wire:loading wire:target="save">Enregistrement…</span></button>@if($article)<a class="secondary-button centered" href="{{ $article->status === 'published' ? $article->public_url : route('admin.articles.preview', $article) }}" target="_blank">Voir la page ↗</a>@endif @if($article)<button type="button" class="secondary-button centered" style="margin-top: 10px;" wire:click="regenerateThumbnail" wire:loading.attr="disabled" wire:target="regenerateThumbnail"><span wire:loading.remove wire:target="regenerateThumbnail">Régénérer Thumbnail</span><span wire:loading wire:target="regenerateThumbnail">Génération…</span></button>@endif</article>
        <article class="panel os-form one-column editor-settings"><h3>Taxonomie & SEO</h3><div class="field"><label>Catégorie</label><input wire:model="categoryName" placeholder="ex. Outils SEO"></div><div class="field"><label>Tags séparés par virgules</label><input wire:model="tagsText" placeholder="SEO, SaaS, PME"></div><div class="field"><label>Mot-clé principal</label><input wire:model="primaryKeyword"></div><div class="field"><label>Intention</label><input wire:model="searchIntent" placeholder="Informationnelle"></div><div class="field"><label>Meta title</label><input wire:model="metaTitle"></div><div class="field"><label>Meta description</label><textarea wire:model="metaDescription" rows="3"></textarea></div><div class="field"><label>Canonical personnalisée</label><input wire:model="canonicalUrl" type="url"></div></article>
        
    </aside></form>
</div>
