<div class="dashboard-page os-page">
    <section class="page-heading"><div><span class="eyebrow dark">Génération assistée</span><h1>Studio de contenu</h1><p>Gemini transforme vos preuves en brouillons cités — jamais en promesses de classement.</p></div></section>
    @unless($hasApiKey)<a class="setup-banner" href="{{ route('admin.settings') }}" wire:navigate><span>✦</span><div><strong>Clé Gemini requise</strong><p>Configurez une clé API pour activer la génération.</p></div><b>Configurer →</b></a>@endunless
    @if($message)<div class="alert success">✓ {{ $message }}</div>@endif @if($error)<div class="alert danger">{{ $error }}</div>@endif
    <section class="studio-layout">
        <aside class="panel generator-panel"><div class="panel-head"><div><h2>Nouveau brouillon</h2><p>Contexte + intention + preuves</p></div></div><form wire:submit="generate" class="os-form one-column">
            <div class="field"><label>Projet</label><select wire:model.live="projectId"><option value="">Sélectionner</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->name }}</option>@endforeach</select></div>
            <div class="field"><label>Type de contenu</label><select wire:model.live="type"><option value="tool_review">Fiche détaillée</option><option value="pricing">Page tarifs</option><option value="comparison">Comparatif direct</option><option value="best_tools">Meilleures solutions</option><option value="alternatives">Alternatives</option><option value="informational">Article informationnel</option></select></div>
            <div class="structure-preview"><span>{{ $contentStructure['label'] }}</span><strong>{{ $contentStructure['target_min'] }}–{{ $contentStructure['target_max'] }} mots</strong><small>{{ count($contentStructure['sections']) }} sections obligatoires · tableau · FAQ · contrôle automatique</small></div>
            <div class="field"><label>Mot-clé principal</label><select wire:model="keywordId"><option value="">Sans mot-clé importé</option>@foreach($keywords as $keyword)<option value="{{ $keyword->id }}">{{ $keyword->keyword }} ({{ round($keyword->opportunity_score) }})</option>@endforeach</select></div>
            <div class="field"><label>Consignes éditoriales</label><textarea wire:model="instructions" rows="5" placeholder="Angle, audience, ton, éléments à traiter…"></textarea></div>
            <div class="grounding-note"><span>✓</span><p><strong>Mode preuves uniquement</strong>Les faits non vérifiés seront marqués « non communiqué » et les citations [S1] seront obligatoires.</p></div>
            <button class="primary-button form-submit" type="submit" @disabled(!$hasApiKey)><span wire:loading.remove wire:target="generate">✦ Générer avec Gemini</span><span wire:loading wire:target="generate">Génération en cours…</span></button>
        </form></aside>
        <article class="panel preview-panel"><div class="panel-head"><div><h2>Aperçu du brouillon</h2><p>Validation humaine obligatoire</p></div>@if($selectedArticle)<div class="preview-actions"><span class="state-badge review">{{ $selectedArticle->status }}</span>@if($selectedArticle->status !== 'published')<button class="small-primary" wire:click="publish({{ $selectedArticle->id }})" wire:confirm="Confirmer la relecture et publier cet article sur le blog ?">Publier</button>@else<a href="{{ route('blog.show',$selectedArticle->slug) }}" target="_blank">Voir ↗</a>@endif</div>@endif</div>
            @if($selectedArticle)<div class="article-meta"><h2>{{ $selectedArticle->title }}</h2><p>{{ $selectedArticle->meta_description }}</p><div><span>/{{ $selectedArticle->slug }}</span><span>{{ $selectedArticle->generated_by }}</span><span>{{ count($selectedArticle->source_ids ?? []) }} sources</span></div></div>@if($selectedArticle->brief)<div class="brief-card"><span>Brief SEO · {{ $selectedArticle->topic_fingerprint }}</span><h3>{{ $selectedArticle->brief->angle }}</h3><p>Audience : {{ $selectedArticle->brief->audience }} · Intention : {{ $selectedArticle->brief->search_intent ?: 'à valider' }}</p><p><strong>Promesse :</strong> {{ $selectedArticle->brief->unique_promise }}</p><p><strong>Sujets exclus :</strong> {{ collect($selectedArticle->brief->excluded_topics)->implode(' · ') }}</p><ol>@foreach($selectedArticle->brief->outline as $point)<li>{{ $point }}</li>@endforeach</ol></div>@endif<div class="quality-row">@foreach($selectedArticle->quality_checks ?? [] as $label=>$ok)<span class="{{ $ok ? 'ok':'warn' }}">{{ $ok ? '✓':'!' }} {{ str_replace('_',' ',$label) }}</span>@endforeach</div><div class="markdown-body">{!! $this->previewHtml($selectedArticle) !!}</div>@else<div class="empty-preview"><span>✦</span><h3>Votre prochain contenu apparaîtra ici</h3><p>Choisissez un projet avec des sources vérifiées, puis lancez la génération.</p></div>@endif
        </article>
    </section>
    @if($articles->isNotEmpty())<article class="panel article-library"><div class="panel-head"><div><h2>Bibliothèque</h2><p>Derniers brouillons générés</p></div></div><div class="article-list">@foreach($articles as $article)<button wire:click="selectArticle({{ $article->id }})" class="{{ $selectedArticle?->id === $article->id ? 'active':'' }}"><span>{{ strtoupper(substr($article->title,0,1)) }}</span><div><strong>{{ $article->title }}</strong><small>{{ $article->project->name }} · {{ $article->created_at->diffForHumans() }}</small></div><b>{{ $article->status }}</b></button>@endforeach</div></article>@endif
</div>
