<div class="dashboard-page os-page" @if($activeSourceId) wire:poll.2s="refreshCrawlStatus" @endif>
    <section class="page-heading"><div><span class="eyebrow dark">Research</span><h1>Collecte & preuves</h1><p>Crawlez une page publique et conservez chaque fait avec sa source et sa date.</p></div></section>
    @if($message)<div class="alert success">✓ {{ $message }}</div>@endif @if($error)<div class="alert danger">{{ $error }}</div>@endif
    <article class="panel compact-form-panel"><form wire:submit="crawl" class="inline-form">
        <div class="field"><label>Projet</label><select wire:model.live="projectId"><option value="">Sélectionner</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->name }}</option>@endforeach</select></div>
        <div class="field"><label>Type de page</label><select wire:model.live="type"><option value="homepage">Accueil</option><option value="pricing">Tarifs</option><option value="features">Fonctionnalités</option><option value="integrations">Intégrations</option><option value="faq">FAQ</option><option value="documentation">Documentation</option><option value="other">Autre</option></select></div>
        <div class="field grow"><label>URL publique</label><input wire:model="url" type="url" placeholder="https://..."></div>
        <button class="primary-button" type="submit"><span wire:loading.remove wire:target="crawl">Collecter la page</span><span wire:loading wire:target="crawl">Mise en file…</span></button>
    </form><p class="form-note">Le crawler respecte robots.txt, limite la taille à 5 Mo et refuse les adresses réseau privées.</p></article>
    <section class="dashboard-grid research-grid"><article class="panel"><div class="panel-head"><div><h2>Sources collectées</h2><p>Traçabilité de la base de preuves</p></div></div>@if($selectedIds)<div class="bulk-toolbar"><strong>{{ count($selectedIds) }} sélectionnée(s)</strong><button type="button" wire:click="clearSelection">Annuler</button><button class="danger" type="button" wire:click="deleteSelected" wire:confirm="Supprimer définitivement les sources, leurs preuves et les tarifs associés ?">Supprimer</button></div>@endif<div class="table-wrap"><table><thead><tr><th class="selection-cell"><input type="checkbox" wire:model.live="selectAll" aria-label="Tout sélectionner"></th><th>Source</th><th>Type</th><th>Preuves</th><th>Confiance</th><th>Vérification</th></tr></thead><tbody>@forelse($sources as $source)<tr class="{{ in_array($source->id,$selectedIds) ? 'is-selected':'' }}"><td class="selection-cell"><input type="checkbox" wire:model.live="selectedIds" value="{{ $source->id }}" aria-label="Sélectionner {{ $source->title ?: 'la source' }}"></td><td><div class="source-cell"><strong>{{ $source->title ?: 'Sans titre' }}</strong><a href="{{ $source->url }}" target="_blank" rel="noopener">{{ Str::limit($source->url,55) }}</a>@if($source->error_message)<small>{{ $source->error_message }}</small>@endif</div></td><td><span class="role-badge">{{ $source->type }}</span></td><td>{{ $source->evidence_chunks_count }}</td><td>{{ round($source->confidence_score*100) }}%</td><td><span class="verified"><i></i>{{ $source->verified_at?->diffForHumans() ?? $source->status }}</span></td></tr>@empty<tr><td colspan="6" class="empty-state">Aucune source. Lancez une première collecte.</td></tr>@endforelse</tbody></table></div></article>
        <aside class="panel"><div class="panel-head"><div><h2>Prix normalisés</h2><p>Formules consolidées à contrôler</p></div></div><div class="price-list">@forelse($plans as $plan)<div><b>{{ $plan->name }}</b><strong>{{ $plan->formattedPriceRange() }}</strong><span>{{ $plan->displayPeriod() ?: 'Conditions variables' }}</span><small>{{ Str::limit($plan->raw_price,140) }}</small></div>@empty<p class="empty-state">Collectez une page de type Tarifs.</p>@endforelse</div></aside>
    </section>
</div>
